server:
  port: 8082

spring:
  application:
    name: payment-service

  # Docker 환경에서는 컨테이너 이름으로 접속
  datasource:
    url: jdbc:postgresql://postgres:5432/payment_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: payment-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

outbox:
  topic: payment-events
  polling-ms: 200
