spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/user_service
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      cluster:
        nodes:
          - redis-node-1:7001
          - redis-node-2:7002
          - redis-node-3:7003
          - redis-node-4:7004
          - redis-node-5:7005
          - redis-node-6:7006

logging:
  level:
    com.eventfulcommerce.user: DEBUG
    org.springframework.security: DEBUG
