server:
  port: 8081

spring:
  profiles:
    default: dev
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/order_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 테이블 자동 생성/업데이트 (개발용)
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: order-service-group
      auto-offset-reset: earliest

  # 모든 노드를 적는 이유는 1개만 설정했을 때 해당 노드가 죽어있을 수 있음.
  data:
    redis:
      cluster:
        nodes:
          - redis-cluster.local:7001
          - redis-cluster.local:7002
          - redis-cluster.local:7003
          - redis-cluster.local:7004
          - redis-cluster.local:7005
          - redis-cluster.local:7006
        max-redirects: 3 # MOVED 응답 시 최대 재시도 횟수

#  flyway:
#    enabled: true
#    locations: classpath:db/migration

outbox:
  topic: order-events
  polling-ms: 200

jwt:
  secret: ${JWT_SECRET:}

#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.orm.jdbc.bind: trace   # 파라미터 바인딩 로그(너무 시끄러우면 info로)
