server:
  port: 8086

spring:
  profiles:
    default: dev
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://localhost:5432/product_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

outbox:
  topic: product-events

jwt:
  secret: ${JWT_SECRET:}

management:
  endpoints:
    web:
      exposure:
        include: health,info

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/product_service
  kafka:
    bootstrap-servers: kafka:9092

jwt:
  secret: ${JWT_SECRET}
