server:
  port: 8086

spring:
  application:
    name: product-service

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB

  datasource:
    url: jdbc:postgresql://localhost:5432/product_service
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

outbox:
  topic: product-events

jwt:
  secret: ${JWT_SECRET:}

image:
  upload-dir: ./uploads/images
  base-url: http://localhost/images

management:
  endpoints:
    web:
      exposure:
        include: health,info
